<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>

<div class="container">
<?php 
echo $this->tag->linkTo(
   [ 'login',
    'Login Up Here!',
    'class'=>'btn btn-outline-success my-2 my-sm-0']
);
?>  
    <?php echo $this->getContent(); ?>
</div>
</body>
</html>