<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>

<div class="container">
<?php 
  if (!$this->cookies->has("login-action"))
  {
    echo $this->tag->linkTo(
        [ 'login',
         'Login Up Here!',
         'class'=>'btn btn-outline-success my-2 my-sm-0']
     );
  }
  else{ 
    $loginCookie = $this->cookies->get("login-action");
    $value = json_decode($loginCookie->getValue());
    echo "bearer=".$value->token;
    echo "<br>";
    echo $this->tag->linkTo(
        [ 'index/logout',
         'Log Out ',
         'class'=>'btn btn-outline-success my-2 my-sm-0']
     );
  }

?>  


    <?php echo $this->getContent(); ?>
</div>
</body>
</html>